# SPDX-FileCopyrightText: 2021-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: chronos-umbrella
description: Chronos Umbrella chart to deploy all Aether ROC
kubeVersion: ">=1.18.0"
type: application
version: 0.1.30
appVersion: v0.0.0
keywords:
  - aether
  - exporter
home: https://www.opennetworking.org/aether/
maintainers:
  - name: Aether Ops team
    email: support@opennetworking.org
dependencies:
  - name: grafana
    condition: import.grafana.enabled
    repository: https://grafana.github.io/helm-charts
    version: 6.16.6 # See also image.tag override for 8.1.8
  - name: prometheus
    condition: import.prometheus.chronos.enabled
    repository: https://prometheus-community.github.io/helm-charts
    version: 14.6.1
    alias: prometheus-chronos
  - name: chronos-exporter
    condition: import.chronos-exporter.enabled
    repository: "file://../chronos-exporter"
    version: 0.1.0
  - name: aether-enterprise-portal
    condition: import.aether-enterprise-portal.enabled
    repository: "file://../aether-enterprise-portal"
    version: 0.1.1
  - name: rasa-model-server
    condition: import.rasa.enabled
    repository: "file://../rasa-model-server"
    version: 0.1.0
  - name: rasa-action-server
    condition: import.rasa.enabled
    repository: "file://../rasa-action-server"
    version: 0.1.0
  - name: rasa
    condition: import.rasa.enabled
    repository: https://helm.rasa.com
    version: 1.16.0
  - name: mailhog
    condition: import.rasa.enabled
    alias: chronos-umbrella-mailhog
    version: 1.0.2
    repository: https://sitepilot.github.io/helm-charts
