# SPDX-FileCopyrightText: 2021-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

nameOverride: ""
fullnameOverride: ""

replicaCount: 1
annotations: {}

image:
  repository: onosproject/subscriber-proxy
  tag: v0.3.2
  pullPolicy: IfNotPresent
  pullSecrets: []

resources:
  requests:
    cpu: 0.5
    memory: 512Mi

service:
  type: ClusterIP

model:
  version: v3

secure: true

config:  
  port: 5000
  webui_endpt:
    addr: aether-roc-umbrella-sdcore-test-dummy
    port: 80
  aether_config_endpt:
    addr: onos-config
    port: 5150
  openidc:
    issuer:
    credentials:
      username: "YWxpY2VhQG9wZW5uZXR3b3JraW5nLm9yZw=="
      password: "cGFzc3dvcmQ="

prometheusEnabled: true

nodeSelector: {}

tolerations: []

affinity: {}

logging:
  loggers:
    root:
      level: info
      output:
        stdout:
          sink: stdout
  sinks:
    stdout:
      type: stdout
      stdout: {}
