{
 "title": "Chronos Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "site", "query": { "query": "label_values(site)" } }
  ]
 },
 "panels": [
  { "title": "Chronos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "datasource" },
  {
   "title": "Device Status",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "device_connected_status{site=\"$site\"}",
     "legendFormat": "{{iccid}}"
    }
   ]
  },
  {
   "title": "Slice Throughput Bytes",
   "type": "timeseries",
   "description": "Stacked Graph series",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "slice_throughput_bytes{site=\"$site\"}",
     "legendFormat": "{{slice}}"
    }
   ]
  },
  {
   "title": "Slice Throughput Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "slice_throughput_bytes{site=\"$site\"}",
     "legendFormat": "{{slice}}"
    }
   ]
  },
  {
   "title": "Slice Latency End-to-End Milliseconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "slice_latency_end_to_end_milliseconds{site=\"$site\"}",
     "legendFormat": "{{slice}},"
    }
   ]
  },
  {
   "title": "Slice Throughput Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "slice_throughput_packets{site=\"$site\"}",
     "legendFormat": "{{slice}}"
    }
   ]
  },
  {
   "title": "Device Connection Event Core",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "device_connection_event_core{site=\"$site\"}",
     "legendFormat": "{{iccid}}"
    }
   ]
  },
  {
   "title": "Device Connection Event Ran",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "device_connection_event_ran{site=\"$site\"}",
     "legendFormat": "{{iccid}}"
    }
   ]
  },
  {
   "title": "Device Connection Event Fabric",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "device_connection_event_fabric{site=\"$site\"}",
     "legendFormat": "{{iccid}}"
    }
   ]
  }
 ]
}