{
 "title": "Chronos Device Connection Events",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "site", "query": { "query": "label_values(site)" } },
   {
    "name": "serial_number",
    "query": {
     "query": "label_values(device_connection_event_core{site=\"$site\"}, serial_number)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Device Connection Event Core",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "device_connection_event_core{site=\"$site\", serial_number=\"$serial_number\"}",
     "legendFormat": "{{iccid}},{{msg}}"
    }
   ]
  },
  {
   "title": "Device Connection Event Ran",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "device_connection_event_ran{site=\"$site\", serial_number=\"$serial_number\"}",
     "legendFormat": "{{iccid}},{{msg}}"
    }
   ]
  },
  {
   "title": "Device Connection Event Fabric",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "device_connection_event_fabric{site=\"$site\", serial_number=\"$serial_number\"}",
     "legendFormat": "{{iccid}},{{msg}}"
    }
   ]
  }
 ]
}