{
 "title": "Chronos Device Throughput and Packet Loss Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "site", "query": { "query": "label_values(site)" } },
   {
    "name": "slice",
    "query": {
     "query": "label_values(per_device_per_application_throughput_bytes{site=\"$site\"}, slice)"
    }
   },
   {
    "name": "serial_number",
    "query": {
     "query": "label_values(per_device_per_application_throughput_bytes{site=\"$site\",  slice=\"$slice\"}, serial_number)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Device per Application Throughput Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "per_device_per_application_throughput_bytes{site=\"$site\", slice=\"$slice\", serial_number=\"$serial_number\"}",
     "legendFormat": "{{serial_number}},{{application}},{{slice}}"
    }
   ]
  },
  {
   "title": "Device per application Throughput Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "per_device_per_application_throughput_packets{site=\"$site\", slice=\"$slice\", serial_number=\"$serial_number\"}",
     "legendFormat": "{{serial_number}}, {{application}},{{slice}}"
    }
   ]
  },
  {
   "title": "Device per Application  Packets Loss",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "per_device_per_application_loss_packets{site=\"$site\", slice=\"$slice\", serial_number=\"$serial_number\"}",
     "legendFormat": "{{serial_number}}, {{application}}, {{slice}}"
    }
   ]
  }
 ]
}