# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0

apiVersion: v2
name: aether-roc-umbrella
description: Aether ROC Umbrella chart to deploy all Aether ROC
kubeVersion: ">=1.18.0"
type: application
version: 1.4.67
appVersion: v0.0.0
keywords:
  - aether
  - sdn
home: https://www.opennetworking.org/aether/
maintainers:
  - name: Aether Ops team
    email: support@opennetworking.org
dependencies:
  - name: onos-topo
    condition: import.onos-topo.enabled
    repository: https://charts.onosproject.org
    version: 1.1.109
  - name: config-model-aether-3
    condition: onos-config.models.aether.v3.enabled
    repository: "file://../config-models/aether-3.x"
    version: 3.0.15
  - name: config-model-aether-4
    condition: onos-config.models.aether.v4.enabled
    repository: "file://../config-models/aether-4.x"
    version: 4.0.17
  - name: config-model-plproxy
    condition: onos-config.models.plproxy.v1.enabled
    repository: "file://../config-models/plproxy-1.x"
    version: 1.0.1
    alias: config-model-plproxy-1-0-0
  - name: onos-config
    condition: import.onos-config.enabled
    repository: https://charts.onosproject.org
    version: 1.4.6
  - name: onos-gui
    condition: import.onos-gui.enabled
    repository: https://charts.onosproject.org
    version: 1.0.8
  - name: onos-cli
    condition: import.onos-cli.enabled
    repository: https://charts.onosproject.org
    version: 1.1.11
  - name: aether-roc-api
    condition: import.aether-roc-api.enabled
    repository: "file://../aether-roc-api"
    version: 1.2.13
  - name: aether-roc-websocket
    condition: import.aether-roc-websocket.enabled
    repository: "file://../aether-roc-websocket"
    version: 1.0.1
  - name: aether-roc-gui
    condition: import.aether-roc-gui.v3.enabled
    repository: "file://../aether-roc-gui"
    version: 3.0.29
  - name: aether-roc-gui-v4
    condition: import.aether-roc-gui.v4.enabled
    repository: "file://../aether-roc-gui-v4"
    version: 4.0.100
  - name: sdcore-adapter
    condition: import.sdcore-adapter.v3.enabled
    repository: "file://../sdcore-adapter"
    version: 3.0.16
  - name: sdcore-adapter-v4
    condition: import.sdcore-adapter.v4.enabled
    repository: "file://../sdcore-adapter-v4"
    version: 4.0.18
  - name: subscriber-proxy
    condition: import.subscriber-proxy.enabled
    repository: "file://../subscriber-proxy"
    version: 0.0.6
  - name: nginx
    alias: sdcore-test-dummy
    condition: import.sdcore-test-dummy.enabled
    repository: https://charts.bitnami.com/bitnami
    version: 8.9.0
  - name: grafana
    condition: import.grafana.enabled
    repository: https://grafana.github.io/helm-charts
    version: 6.16.6
  - name: prometheus
    condition: import.prometheus.amp.enabled
    repository: https://prometheus-community.github.io/helm-charts
    version: 14.6.1
    alias: prometheus-amp
  - name: prometheus
    condition: import.prometheus.acc.enabled
    repository: https://prometheus-community.github.io/helm-charts
    version: 14.6.1
    alias: prometheus-acc
  - name: prometheus
    condition: import.prometheus.ace.enabled
    repository: https://prometheus-community.github.io/helm-charts
    version: 14.6.1
    alias: prometheus-ace
  - name: prom-label-proxy
    condition: import.prom-label-proxy.amp.enabled
    repository: "file://../prom-label-proxy"
    version: 0.0.3
    alias: prom-label-proxy-amp
  - name: prom-label-proxy
    condition: import.prom-label-proxy.acc.enabled
    repository: "file://../prom-label-proxy"
    version: 0.0.3
    alias: prom-label-proxy-acc
  - name: demo-exporter
    condition: import.demo-exporter.enabled
    repository: "file://../demo-exporter"
    version: 0.0.1
