# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: aether-roc-umbrella
description: Aether ROC Umbrella chart to deploy all Aether ROC
kubeVersion: ">=1.18.0"
type: application
version: 2.0.36
appVersion: v0.0.0
keywords:
  - aether
  - sdn
home: https://www.opennetworking.org/aether/
maintainers:
  - name: Aether Ops team
    email: support@opennetworking.org
dependencies:
  - name: onos-topo
    condition: import.onos-topo.enabled
    repository: https://charts.onosproject.org
    version: 1.2.2
  - name: onos-config
    condition: import.onos-config.enabled
    repository: https://charts.onosproject.org
    version: 1.6.9
  - name: onos-cli
    condition: import.onos-cli.enabled
    repository: https://charts.onosproject.org
    version: 1.2.7
  - name: aether-roc-api
    condition: import.aether-roc-api.enabled
    repository: "file://../aether-roc-api"
    version: 1.5.0
  - name: aether-roc-websocket
    condition: import.aether-roc-websocket.enabled
    repository: "file://../aether-roc-websocket"
    version: 1.1.1
  - name: aether-roc-gui-v4
    condition: import.aether-roc-gui.v4.enabled
    repository: "file://../aether-roc-gui-v4"
    version: 4.0.16
  - name: aether-roc-gui-v2
    condition: import.aether-roc-gui.v2.enabled
    repository: "file://../aether-roc-gui-v2"
    version: 2.0.8
  - name: sdcore-adapter-v2
    condition: import.sdcore-adapter.v2.enabled
    repository: "file://../sdcore-adapter-v2"
    version: 2.0.8
  - name: sdcore-adapter-v4
    condition: import.sdcore-adapter.v4.enabled
    repository: "file://../sdcore-adapter-v4"
    version: 4.0.19
  - name: subscriber-proxy
    condition: import.subscriber-proxy.enabled
    repository: "file://../subscriber-proxy"
    version: 0.1.4
  - name: nginx
    alias: sdcore-test-dummy
    condition: import.sdcore-test-dummy.enabled
    repository: https://charts.bitnami.com/bitnami
    version: 8.9.0
  - name: grafana
    condition: import.grafana.enabled
    repository: https://grafana.github.io/helm-charts
    version: 6.16.6
  - name: prometheus
    condition: import.prometheus.amp.enabled
    repository: https://prometheus-community.github.io/helm-charts
    version: 14.6.1
    alias: prometheus-amp
  - name: prometheus
    condition: import.prometheus.acc.enabled
    repository: https://prometheus-community.github.io/helm-charts
    version: 14.6.1
    alias: prometheus-acc
  - name: prometheus
    condition: import.prometheus.ace.enabled
    repository: https://prometheus-community.github.io/helm-charts
    version: 14.6.1
    alias: prometheus-ace
  - name: prom-label-proxy
    condition: import.prom-label-proxy.amp.enabled
    repository: "file://../prom-label-proxy"
    version: 0.1.2
    alias: prom-label-proxy-amp
  - name: prom-label-proxy
    condition: import.prom-label-proxy.acc.enabled
    repository: "file://../prom-label-proxy"
    version: 0.1.2
    alias: prom-label-proxy-acc
  - name: demo-exporter
    condition: import.demo-exporter.enabled
    repository: "file://../demo-exporter"
    version: 0.1.1
