# SPDX-FileCopyrightText: 2022-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "rasa-action-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ template "rasa-action-server.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rasa-action-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        name: {{ template "rasa-action-server.fullname" . }}
        {{- include "rasa-action-server.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          args:
            - "/usr/local/bin/rasa-action-server"
            - "--smtpServer"
            - {{.Values.smtp.server | quote }}
            - "--smtpSerPort"
            - {{.Values.smtp.port | quote}}
          ports:
            - name: action
              containerPort: 8081
          readinessProbe:
            httpGet:
              path: /webhook
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /webhook
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
