# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Intel Corporation

name: Tag/Publish Release

on:
  push:
    branches:
      - master

jobs:
  # CAUTION: Other actions depend on this name "tag-github"
  tag-github:
    uses: onosproject/.github/.github/workflows/tag-github.yml@main
    secrets: inherit

  publish:
    needs: tag-github
    if: github.repository_owner == 'onosproject'
    uses: onosproject/.github/.github/workflows/helm-publish-umbrella.yml@main
    with:
      umbrella_charts: ./aether-roc-umbrella
      remote_host: static.opennetworking.org
      remote_path: /srv/sites/charts.aetherproject.org/
    secrets: inherit

  update-version:
    needs: tag-github
    if: needs.tag-github.outputs.changed == 'true'
    uses: onosproject/.github/.github/workflows/bump-version.yml@main
    secrets: inherit
    with:
      version: ${{ needs.tag-github.outputs.version }}
